// Generated by Framer (dc3a148)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["QRrPi8Hfx", "zpLmFOEgi", "QpXYhnhBp"];
const serializationHash = "framer-EeLdV";
const variantClassNames = {
  QpXYhnhBp: "framer-v-1ieyuzk",
  QRrPi8Hfx: "framer-v-1gyeocb",
  zpLmFOEgi: "framer-v-1lkjq2u",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = { bounce: 0, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Premium-Enterprise": "QpXYhnhBp",
  "Premium-Starter": "zpLmFOEgi",
  Free: "QRrPi8Hfx",
};
const getProps = ({
  enterprise,
  free,
  height,
  id,
  premium,
  starter,
  width,
  ...props
}) => {
  return {
    ...props,
    F_VsFm9LO: premium ?? props.F_VsFm9LO ?? "Premium",
    MpnqRzg5C: starter ?? props.MpnqRzg5C ?? "Starter",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "QRrPi8Hfx",
    XeAcYMmv7: enterprise ?? props.XeAcYMmv7 ?? "Enterprise",
    yCRfSSJvf: free ?? props.yCRfSSJvf ?? "Free",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    yCRfSSJvf,
    F_VsFm9LO,
    MpnqRzg5C,
    XeAcYMmv7,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "QRrPi8Hfx",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap12uvthn = activeVariantCallback(async (...args) => {
    setVariant("QRrPi8Hfx");
  });
  const onTap1jiqg8 = activeVariantCallback(async (...args) => {
    setVariant("zpLmFOEgi");
  });
  const onTap1or78u5 = activeVariantCallback(async (...args) => {
    setVariant("QpXYhnhBp");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1gyeocb",
            className,
            classNames,
          ),
          "data-border": true,
          "data-framer-name": "Free",
          layoutDependency: layoutDependency,
          layoutId: "QRrPi8Hfx",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgba(26, 26, 26, 0.09)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(255, 255, 255)",
            borderBottomLeftRadius: 165,
            borderBottomRightRadius: 165,
            borderTopLeftRadius: 165,
            borderTopRightRadius: 165,
            ...style,
          },
          ...addPropertyOverrides(
            {
              QpXYhnhBp: { "data-framer-name": "Premium-Enterprise" },
              zpLmFOEgi: { "data-framer-name": "Premium-Starter" },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1iy48vg",
              "data-framer-name": "Free",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "h8yN3jEip",
              onTap: onTap12uvthn,
              style: {
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
              },
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "SW50ZXItTWVkaXVt",
                      "--framer-font-family":
                        '"Inter", "Inter Placeholder", sans-serif',
                      "--framer-font-weight": "500",
                      "--framer-letter-spacing": "-0.03em",
                      "--framer-line-height": "1em",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(242, 247, 255))",
                    },
                    children: "Free",
                  }),
                }),
                className: "framer-1xr0sqo",
                draggable: "false",
                fonts: ["Inter-Medium"],
                layoutDependency: layoutDependency,
                layoutId: "fwaPjYNUL",
                style: {
                  "--extracted-r6o4lv": "rgb(242, 247, 255)",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: yCRfSSJvf,
                variants: {
                  QpXYhnhBp: { "--extracted-r6o4lv": "rgb(44, 44, 46)" },
                  zpLmFOEgi: { "--extracted-r6o4lv": "rgb(44, 44, 46)" },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    QpXYhnhBp: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.03em",
                            "--framer-line-height": "1em",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(44, 44, 46))",
                          },
                          children: "Free",
                        }),
                      }),
                    },
                    zpLmFOEgi: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.03em",
                            "--framer-line-height": "1em",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(44, 44, 46))",
                          },
                          children: "Free",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-q7qv96",
              "data-framer-name": "Premium",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "IRRBvkyRc",
              onTap: onTap1jiqg8,
              style: {
                backgroundColor: "rgba(26, 26, 26, 0)",
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
              },
              ...addPropertyOverrides(
                {
                  zpLmFOEgi: { "data-highlight": undefined, onTap: undefined },
                },
                baseVariant,
                gestureVariant,
              ),
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "SW50ZXItTWVkaXVt",
                        "--framer-font-family":
                          '"Inter", "Inter Placeholder", sans-serif',
                        "--framer-font-weight": "500",
                        "--framer-letter-spacing": "-0.03em",
                        "--framer-line-height": "1em",
                        "--framer-text-color-rgb": "rgb(33.15, 38.25, 43.35)",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, color(display-p3 0.13703465982028243 0.14803474152763713 0.1707317073170732))",
                      },
                      children: "Premium",
                    }),
                  }),
                  className: "framer-1e5pclg",
                  draggable: "false",
                  fonts: ["Inter-Medium"],
                  layoutDependency: layoutDependency,
                  layoutId: "ti1pYZEsA",
                  style: {
                    "--extracted-r6o4lv":
                      "color(display-p3 0.13703465982028243 0.14803474152763713 0.1707317073170732)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                  },
                  text: F_VsFm9LO,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      QpXYhnhBp: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "SW50ZXItTWVkaXVt",
                              "--framer-font-family":
                                '"Inter", "Inter Placeholder", sans-serif',
                              "--framer-font-size": "14px",
                              "--framer-font-weight": "500",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1em",
                              "--framer-text-color-rgb":
                                "rgb(33.15, 38.25, 43.35)",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, color(display-p3 0.13703465982028243 0.14803474152763713 0.1707317073170732))",
                            },
                            children: "Premium",
                          }),
                        }),
                        transformTemplate: transformTemplate1,
                      },
                      zpLmFOEgi: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "SW50ZXItTWVkaXVt",
                              "--framer-font-family":
                                '"Inter", "Inter Placeholder", sans-serif',
                              "--framer-font-size": "14px",
                              "--framer-font-weight": "500",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1em",
                              "--framer-text-color-rgb":
                                "rgb(33.15, 38.25, 43.35)",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, color(display-p3 0.13703465982028243 0.14803474152763713 0.1707317073170732))",
                            },
                            children: "Premium",
                          }),
                        }),
                        transformTemplate: transformTemplate1,
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-12nkb8k",
                  "data-framer-name": "Starter/Enterprise",
                  layoutDependency: layoutDependency,
                  layoutId: "O418MaXVD",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1w7qxyy",
                      "data-framer-name": "Starter",
                      "data-highlight": true,
                      layoutDependency: layoutDependency,
                      layoutId: "f4VMyq1qm",
                      onTap: onTap1jiqg8,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "SW50ZXItTWVkaXVt",
                              "--framer-font-family":
                                '"Inter", "Inter Placeholder", sans-serif',
                              "--framer-font-size": "10px",
                              "--framer-font-weight": "500",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1.1em",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(145, 146, 150))",
                            },
                            children: "Starter",
                          }),
                        }),
                        className: "framer-1awh7j2",
                        draggable: "false",
                        fonts: ["Inter-Medium"],
                        layoutDependency: layoutDependency,
                        layoutId: "tApnQ6umN",
                        style: {
                          "--extracted-r6o4lv": "rgb(145, 146, 150)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        text: MpnqRzg5C,
                        variants: {
                          QpXYhnhBp: {
                            "--extracted-r6o4lv": "rgb(192, 213, 250)",
                          },
                          zpLmFOEgi: {
                            "--extracted-r6o4lv": "rgb(45, 47, 51)",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            QpXYhnhBp: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector": "SW50ZXItTWVkaXVt",
                                    "--framer-font-family":
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    "--framer-font-size": "13px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(192, 213, 250))",
                                  },
                                  children: "Starter",
                                }),
                              }),
                            },
                            zpLmFOEgi: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector": "SW50ZXItTWVkaXVt",
                                    "--framer-font-family":
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    "--framer-font-size": "13px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(45, 47, 51))",
                                  },
                                  children: "Starter",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-18qnyub",
                      "data-framer-name": "Secondary Switcher",
                      layoutDependency: layoutDependency,
                      layoutId: "VsvyYjTQc",
                      style: {
                        backgroundColor: "rgb(150, 151, 156)",
                        borderBottomLeftRadius: 71,
                        borderBottomRightRadius: 71,
                        borderTopLeftRadius: 71,
                        borderTopRightRadius: 71,
                      },
                      variants: {
                        QpXYhnhBp: { backgroundColor: "rgb(255, 255, 255)" },
                        zpLmFOEgi: { backgroundColor: "rgb(255, 255, 255)" },
                      },
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-yjjx8y",
                      "data-framer-name": "Enterprise",
                      "data-highlight": true,
                      layoutDependency: layoutDependency,
                      layoutId: "jguGnfczB",
                      onTap: onTap1or78u5,
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            style: {
                              "--font-selector": "SW50ZXItTWVkaXVt",
                              "--framer-font-family":
                                '"Inter", "Inter Placeholder", sans-serif',
                              "--framer-font-size": "10px",
                              "--framer-font-weight": "500",
                              "--framer-letter-spacing": "-0.03em",
                              "--framer-line-height": "1.1em",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgb(145, 146, 150))",
                            },
                            children: "Enterprise",
                          }),
                        }),
                        className: "framer-1re7uov",
                        draggable: "false",
                        fonts: ["Inter-Medium"],
                        layoutDependency: layoutDependency,
                        layoutId: "Ok1cPg6s0",
                        style: {
                          "--extracted-r6o4lv": "rgb(145, 146, 150)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        text: XeAcYMmv7,
                        variants: {
                          QpXYhnhBp: {
                            "--extracted-r6o4lv": "rgb(45, 47, 51)",
                          },
                          zpLmFOEgi: {
                            "--extracted-r6o4lv": "rgb(192, 213, 250)",
                          },
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides(
                          {
                            QpXYhnhBp: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector": "SW50ZXItTWVkaXVt",
                                    "--framer-font-family":
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    "--framer-font-size": "13px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(45, 47, 51))",
                                  },
                                  children: "Enterprise",
                                }),
                              }),
                            },
                            zpLmFOEgi: {
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  style: {
                                    "--font-selector": "SW50ZXItTWVkaXVt",
                                    "--framer-font-family":
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    "--framer-font-size": "13px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "1.1em",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(192, 213, 250))",
                                  },
                                  children: "Enterprise",
                                }),
                              }),
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                      }),
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1ffao5h",
              "data-framer-name": "Main Switcher",
              layoutDependency: layoutDependency,
              layoutId: "rwoox5nkQ",
              style: {
                backgroundColor: "var(--1jt8ng8, rgb(0, 84.15, 255))",
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
              },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-EeLdV.framer-1fhbidz, .framer-EeLdV .framer-1fhbidz { display: block; }",
  ".framer-EeLdV.framer-1gyeocb { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 3px; position: relative; width: 342px; }",
  ".framer-EeLdV .framer-1iy48vg { align-content: center; align-items: center; cursor: pointer; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 37px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
  ".framer-EeLdV .framer-1xr0sqo, .framer-EeLdV .framer-1e5pclg { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-EeLdV .framer-q7qv96 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 37px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
  ".framer-EeLdV .framer-12nkb8k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
  ".framer-EeLdV .framer-1w7qxyy, .framer-EeLdV .framer-yjjx8y { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; z-index: 4; }",
  ".framer-EeLdV .framer-1awh7j2, .framer-EeLdV .framer-1re7uov { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; z-index: 3; }",
  ".framer-EeLdV .framer-18qnyub { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 3px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 3px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-EeLdV .framer-1ffao5h { bottom: 3px; flex: none; gap: 10px; left: 3px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 3px; width: 49%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  "@supports (color: color(display-p3 1 1 1)) { .framer-EeLdV { --1jt8ng8: color(display-p3 0 0.32644052000111534 1); } }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-q7qv96 { cursor: unset; }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-1e5pclg, .framer-EeLdV.framer-v-1ieyuzk .framer-1e5pclg { left: 50%; position: absolute; top: -21px; z-index: 1; }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-12nkb8k, .framer-EeLdV.framer-v-1ieyuzk .framer-12nkb8k { flex: 1 0 0px; gap: 0px; height: 1px; }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-1w7qxyy, .framer-EeLdV.framer-v-1lkjq2u .framer-yjjx8y, .framer-EeLdV.framer-v-1ieyuzk .framer-1w7qxyy, .framer-EeLdV.framer-v-1ieyuzk .framer-yjjx8y { flex: 1 0 0px; height: 100%; padding: 8px 16px 8px 16px; width: 1px; }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-18qnyub { aspect-ratio: unset; bottom: 2px; height: unset; left: 0px; position: absolute; top: 2px; width: 50%; z-index: 1; }",
  ".framer-EeLdV.framer-v-1lkjq2u .framer-1ffao5h, .framer-EeLdV.framer-v-1ieyuzk .framer-1ffao5h { left: unset; right: 3px; width: 50%; }",
  ".framer-EeLdV.framer-v-1ieyuzk .framer-18qnyub { aspect-ratio: unset; bottom: 2px; height: unset; position: absolute; right: 2px; top: 2px; width: 49%; z-index: 1; }",
  '.framer-EeLdV[data-border="true"]::after, .framer-EeLdV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 43
 * @framerIntrinsicWidth 342
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"zpLmFOEgi":{"layout":["fixed","auto"]},"QpXYhnhBp":{"layout":["fixed","auto"]}}}
 * @framerVariables {"yCRfSSJvf":"free","F_VsFm9LO":"premium","MpnqRzg5C":"starter","XeAcYMmv7":"enterprise"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerkpd_DU3Jq = withCSS(Component, css, "framer-EeLdV");
export default Framerkpd_DU3Jq;
Framerkpd_DU3Jq.displayName = "DynamicToggle";
Framerkpd_DU3Jq.defaultProps = { height: 43, width: 342 };
addPropertyControls(Framerkpd_DU3Jq, {
  variant: {
    options: ["QRrPi8Hfx", "zpLmFOEgi", "QpXYhnhBp"],
    optionTitles: ["Free", "Premium-Starter", "Premium-Enterprise"],
    title: "Variant",
    type: ControlType.Enum,
  },
  yCRfSSJvf: {
    defaultValue: "Free",
    displayTextArea: false,
    title: "Free",
    type: ControlType.String,
  },
  F_VsFm9LO: {
    defaultValue: "Premium",
    displayTextArea: false,
    title: "Premium",
    type: ControlType.String,
  },
  MpnqRzg5C: {
    defaultValue: "Starter",
    displayTextArea: false,
    title: "Starter",
    type: ControlType.String,
  },
  XeAcYMmv7: {
    defaultValue: "Enterprise",
    displayTextArea: false,
    title: "Enterprise",
    type: ControlType.String,
  },
});
addFonts(
  Framerkpd_DU3Jq,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
          weight: "500",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerkpd_DU3Jq",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "43",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "342",
        framerVariables:
          '{"yCRfSSJvf":"free","F_VsFm9LO":"premium","MpnqRzg5C":"starter","XeAcYMmv7":"enterprise"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"zpLmFOEgi":{"layout":["fixed","auto"]},"QpXYhnhBp":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./kpd_DU3Jq.map
